apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enterprise-data-platform
resources:
  - namespace.yaml
  - config.yaml
  - api
  - workers.yaml
  - availability.yaml
  - network.yaml
