apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: edp-indexing
    $patch: delete
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: edp-export
    $patch: delete
- target:
    kind: ConfigMap
    name: edp-config
  patch: |-
    - op: replace
      path: /data/EDP_SEARCH_URL
      value: ""
    - op: replace
      path: /data/EDP_EMBEDDING_URL
      value: ""
    - op: replace
      path: /data/EDP_EXPORT_BUCKET
      value: ""
    - op: replace
      path: /data/EDP_EXPORT_KMS_KEY_ID
      value: ""
