export const RESOURCES = {
  sources: { title: 'Sources', singular: 'source', icon: 'source', color: 'blue', description: 'Connect and inspect governed source systems.',
    fields: [['id','Source ID'],['kind','Connector','select','postgres,mysql,mariadb,snowflake,denodo,sqlalchemy,rest'],['secret_ref','Secret reference'],['enabled','Enabled','boolean'],['pool_size','Connection pool size','number'],['statement_timeout_seconds','Statement timeout (seconds)','number'],['max_scan_rows','Maximum scan rows','number'],['endpoint','REST endpoint'],['allowed_hosts','Allowed REST hosts','list'],['options','Connector options','json']],
    defaults: { id: '', kind: 'postgres', secret_ref: 'file://', enabled: false, pool_size: 8, pool_timeout_seconds: 2, statement_timeout_seconds: 15, max_scan_rows: 1000000, native_scan_governor: false, endpoint: null, allowed_hosts: [], options: {} },
    columns: [['id','Source'],['kind','Connector'],['enabled','Enabled'],['pool_size','Pool size'],['statement_timeout_seconds','Timeout (s)']] },
  datasets: { title: 'Data Products', singular: 'data product', icon: 'database', color: 'violet', description: 'Publish discoverable data contracts with explicit access and retrieval capabilities.',
    fields: [['id','Dataset ID'],['display_name','Display name'],['description','Description'],['version','New immutable version'],['status','Status','select','draft,active,degraded,disabled'],['source','Source binding','json'],['identity_fields','Identity fields','list'],['fields','Field definitions','json'],['capabilities','Capabilities','list'],['mandatory_filter','Mandatory row filter','json'],['tenant_field','Tenant field'],['retrieval','Retrieval profile','json'],['max_limit','Maximum page size','number'],['max_top_k','Maximum top K','number']],
    defaults: { id: '', display_name: '', version: '1', status: 'draft', source: {}, identity_fields: [], fields: [], capabilities: ['query'], mandatory_filter: null, tenant_field: null, retrieval: null, max_limit: 1000, max_top_k: 100 },
    columns: [['display_name','Data product'],['status','Status'],['version','Version'],['capabilities','Capabilities'],['source','Source']] },
  policies: { title: 'Policies', singular: 'policy', icon: 'shield', color: 'teal', description: 'Control who can access each data product, operation, and field.',
    fields: [['id','Policy ID'],['effect','Effect','select','deny,allow'],['enabled','Enabled','boolean'],['dataset_patterns','Dataset patterns','list'],['operations','Operations','list'],['client_ids','Consumer IDs','list'],['groups','Identity groups','list'],['subjects','Subjects','list'],['tenants','Tenants','list'],['allowed_fields','Allowed fields','json'],['denied_fields','Denied fields','list'],['mandatory_filter','Row filter','json'],['require_tenant_isolation','Require tenant isolation','boolean'],['max_limit','Maximum page size','number'],['max_top_k','Maximum top K','number'],['priority','Priority','number']],
    defaults: { id: '', effect: 'deny', enabled: true, dataset_patterns: [], operations: [], client_ids: [], groups: [], subjects: [], tenants: [], allowed_fields: null, denied_fields: [], mandatory_filter: null, require_tenant_isolation: false, max_limit: 100, max_top_k: 20, priority: 100 },
    columns: [['id','Policy'],['effect','Effect'],['dataset_patterns','Datasets'],['operations','Operations'],['enabled','Enabled']] },
  clients: { title: 'Consumers', singular: 'consumer', icon: 'users', color: 'blue', description: 'Register application identities and set dataset grants and request limits.',
    fields: [['id','OAuth client ID'],['display_name','Display name'],['owner','Owner'],['status','Status','select','disabled,active,degraded'],['auth_mode','Identity mode','select','oauth2,workload_identity,mtls,legacy_api_key'],['environment','Environment'],['allowed_datasets','Allowed dataset IDs','list'],['allowed_capabilities','Allowed capabilities','list'],['rate_limit_rps','Requests per second','number'],['max_concurrency','Maximum concurrency','number']],
    defaults: { id: '', display_name: '', owner: '', status: 'disabled', auth_mode: 'oauth2', environment: '', allowed_datasets: [], allowed_capabilities: [], rate_limit_rps: 50, max_concurrency: 20 },
    columns: [['display_name','Consumer'],['owner','Owner'],['status','Status'],['auth_mode','Identity'],['allowed_datasets','Datasets']] },
  agents: { title: 'Agents', singular: 'agent', icon: 'bot', color: 'violet', description: 'Bind agents to service identities, approved data products, and context limits.',
    fields: [['id','Agent ID'],['display_name','Display name'],['owner','Owner'],['service_principal','Service principal'],['status','Status','select','disabled,active,degraded'],['allowed_datasets','Allowed dataset IDs','list'],['allowed_capabilities','Allowed capabilities','list'],['mcp_enabled','Enable MCP facade','boolean'],['require_citations','Require citations','boolean'],['allow_raw_vector_input','Allow numeric vectors','boolean'],['max_top_k','Maximum top K','number'],['max_context_chars','Maximum context characters','number'],['max_tool_calls_per_minute','Tool calls per minute','number']],
    defaults: { id: '', display_name: '', owner: '', service_principal: '', status: 'disabled', allowed_datasets: [], allowed_capabilities: [], mcp_enabled: false, require_citations: true, allow_raw_vector_input: false, max_top_k: 20, max_context_chars: 100000, max_tool_calls_per_minute: 60 },
    columns: [['display_name','Agent'],['status','Status'],['service_principal','Service identity'],['mcp_enabled','MCP facade'],['allowed_datasets','Datasets']] },
  guardrails: { title: 'Guardrails', singular: 'guardrail', icon: 'guard', color: 'amber', description: 'Manage enforced retrieval, privacy, and usage constraints.',
    fields: [['id','Guardrail ID'],['name','Name'],['enabled','Enabled','boolean'],['kind','Kind','select','require_citations,deny_sensitive_export,max_scan_budget,max_top_k,prompt_injection_signal,pii_redaction,content_classification,rate_limit,schema_drift,index_freshness'],['scope','Scope','select','global,dataset,client,agent'],['target','Target ID'],['action','Action','select','deny,redact,limit,audit'],['severity','Severity','select','info,warning,high,critical'],['config','Rule configuration','json']],
    defaults: { id: '', name: '', enabled: false, kind: 'require_citations', scope: 'agent', target: '', action: 'deny', severity: 'high', config: {} },
    columns: [['name','Guardrail'],['kind','Kind'],['scope','Scope'],['action','Action'],['severity','Severity']] },
  indexes: { title: 'Indexes & Pipelines', singular: 'index', icon: 'layers', color: 'teal', description: 'Manage index candidates and governed promotion transitions.',
    fields: [['id','Index ID'],['dataset_id','Dataset ID'],['index_type','Index type','select','keyword,vector'],['active_version','Active version'],['candidate_version','Candidate version'],['shard_count','Shard count','number'],['replica_count','Replica count','number']],
    defaults: { id: '', dataset_id: '', index_type: 'keyword', active_version: '', candidate_version: null, state: 'building', indexed_records: 0, freshness_lag_seconds: 0, shard_count: 1, replica_count: 2 },
    columns: [['id','Index'],['index_type','Type'],['state','Reported state'],['active_version','Active version'],['candidate_version','Candidate'],['freshness_lag_seconds','Reported lag (s)']] },
};
export function displayValue(value) {
  if (value === null || value === undefined || value === '') return '—';
  if (typeof value === 'boolean') return value ? 'Enabled' : 'Disabled';
  if (Array.isArray(value)) return value.join(', ') || 'None';
  if (typeof value === 'object') return value.object_name ? [value.connector, value.schema_name, value.object_name].filter(Boolean).join(' · ') : JSON.stringify(value);
  return String(value);
}
